# Generated by Django 5.0.6 on 2024-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
