# Generated by Django 5.0.6 on 2024-07-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_is_published_book_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reference',
        ),
    ]
